name = "vet24-cr"
compatibility_date = "2026-06-09"

[assets]
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "vet24_db"
database_id = "7b4ee52b-a58a-403b-a05a-6d406a2c93b3"

[[kv_namespaces]]
binding = "SESSION"
id = "b58bf278db0e4f4da22b87d1f21c0d29"

[[send_email]]
name = "EMAIL"
