import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';
const [repo, base, next, out] = process.argv.slice(2);
if (!out) throw Error('Usage: node verify-browser.mjs REPO BASE_CLIENT NEXT_CLIENT OUTPUT');
fs.mkdirSync(out,{recursive:true});
const require=createRequire(path.join(process.env.VET_PLAYWRIGHT_ROOT||repo,'package.json'));
const {chromium,expect}=require('@playwright/test');
const routes=fs.readFileSync(path.join(import.meta.dirname,'visual-routes.txt'),'utf8').replace(/^\uFEFF/,'').trim().split(/\r?\n/);
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.woff2':'font/woff2','.png':'image/png','.jpg':'image/jpeg','.webp':'image/webp'};
async function serve(root){const s=http.createServer((req,res)=>{let f=path.join(root,decodeURIComponent(new URL(req.url,'http://local').pathname)); if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html'); if(!fs.existsSync(f)){res.writeHead(404);res.end('404');return;}res.setHeader('content-type',mime[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).pipe(res);}); await new Promise(r=>s.listen(0,'127.0.0.1',r));return s;}
const servers=await Promise.all([serve(base),serve(next)]);
const urls=servers.map(s=>`http://127.0.0.1:${s.address().port}`);
if(process.env.VET_BASE_URL) urls[0]=process.env.VET_BASE_URL;
if(process.env.VET_NEXT_URL) urls[1]=process.env.VET_NEXT_URL;
const browser=await chromium.launch();
const remote=new Map(), remoteFailures=[], excludedExternal=new Set();
const blank=fs.readFileSync(path.join(repo,'tests/e2e/transparent.png'));
const report={routes,profiles:[],visual:[],interaction:[],remoteFailures,limitations:['Static build servers do not execute Worker endpoints; local API responses mocked for UI only.','Map tiles replaced with transparent images; other external resources fetched once and replayed.','Chromium only; no Safari or real email delivery.']};
async function pageFor(profile){const ctx=await browser.newContext({viewport:{width:profile.width,height:900},deviceScaleFactor:1,locale:'es-CR',timezoneId:'America/Costa_Rica',colorScheme:profile.theme,reducedMotion:'reduce',geolocation:{latitude:9.9981,longitude:-84.1197},permissions:['geolocation']});
 await ctx.addInitScript(({theme})=>{localStorage.setItem('theme',theme);const D=Date;const fixed=new D('2026-09-04T18:00:00.000Z').valueOf();globalThis.Date=class extends D{constructor(...args){super(...(args.length?args:[fixed]));}static now(){return fixed;}};},{theme:profile.theme});
 await ctx.route('**/*',async route=>{const u=new URL(route.request().url());if(['127.0.0.1','localhost'].includes(u.hostname)){if(u.pathname.startsWith('/api/')&&!u.pathname.endsWith('.json'))return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(u.pathname.includes('status-override')?{}:{success:true,mocked:true})});return route.continue();}if(u.hostname.includes('tile.openstreetmap.org'))return route.fulfill({status:200,contentType:'image/png',body:blank});
 if(/(^|\.)(gatekeeperconsent\.com|ezojs\.com|ezoic\.net|ezoic\.com)$/.test(u.hostname)){excludedExternal.add(u.href);return route.fulfill({status:200,contentType:'text/javascript',body:''});}
 if(!remote.has(u.href)) remote.set(u.href,(async()=>{try{const r=await route.fetch({timeout:30000});if(!r.ok())throw Error(`HTTP ${r.status()}`);const body=await r.body();return {status:r.status(),contentType:r.headers()['content-type']||'application/octet-stream',body};}catch(e){remoteFailures.push({url:u.href,error:String(e)});return {status:503,body:''};}})());return route.fulfill(await remote.get(u.href));});
 const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));return {ctx,page,errors};}
async function ready(page,url){const response=await page.goto(url,{waitUntil:'networkidle',timeout:45000});if(response.status()!==200)throw Error(`HTTP ${response.status()} ${url}`);await page.evaluate(()=>document.fonts.ready);await page.addStyleTag({content:'*,*::before,*::after{animation:none!important;transition:none!important;caret-color:transparent!important}'});await page.waitForTimeout(700);}
async function capture(profile,url,name){const {ctx,page,errors}=await pageFor(profile);try{await ready(page,url);const png=await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});return {png,errors};}finally{await ctx.close();}}
const diffPage=await browser.newPage();
async function diff(a,b){return diffPage.evaluate(async ([a,b])=>{const load=s=>new Promise((r,j)=>{const i=new Image();i.onload=()=>r(i);i.onerror=j;i.src=s;});const [x,y]=await Promise.all([load(a),load(b)]);if(x.width!==y.width||x.height!==y.height)return {dimensions:[x.width,x.height,y.width,y.height],different:true};const pixels=i=>{const c=document.createElement('canvas');c.width=i.width;c.height=i.height;const z=c.getContext('2d');z.drawImage(i,0,0);return z.getImageData(0,0,c.width,c.height).data;};const p=pixels(x),q=pixels(y);let n=0;for(let i=0;i<p.length;i+=4)if(p[i]!==q[i]||p[i+1]!==q[i+1]||p[i+2]!==q[i+2]||p[i+3]!==q[i+3])n++;return {pixels:n,total:p.length/4,different:n>0};},[a,b].map(x=>'data:image/png;base64,'+x.toString('base64')));}
async function interaction(profile,origin){const {ctx,page,errors}=await pageFor(profile);const result={};try{await ready(page,origin+'/');const cards=()=>page.locator('#clinicas-grid article:not(.hidden)').count();result.initial=await cards();await page.fill('#search-input','Heredia');await page.waitForTimeout(500);result.search=await cards();await page.fill('#search-input','zzzznoexisteseguro');await expect(page.locator('#empty-state')).toBeVisible();result.empty=await cards();await page.click('#reset-all-filters-empty');await expect(page.locator('#search-input')).toHaveValue('');result.reset=await cards();await page.click('#filter-quick-247');await page.waitForTimeout(300);result.emergency=await cards();await page.click('#filter-quick-247');await page.click('[data-filter-animal="exoticos"]');await page.waitForTimeout(300);result.exotics=await cards();await page.click('#reset-all-filters');await page.click('#btn-use-location');await expect(page.locator('[data-distance-for]').first()).toBeVisible();await page.waitForFunction(()=>{const cards=[...document.querySelectorAll('#clinicas-grid article:not(.hidden)')];const distances=cards.map(c=>{const lat=Number(c.dataset.latitude),lng=Number(c.dataset.longitude);return lat&&lng?Math.hypot(lat-9.9981,(lng+84.1197)*Math.cos(9.9981*Math.PI/180)):Infinity;});return distances[0]===Math.min(...distances);});result.nearest=await page.locator('#clinicas-grid article:not(.hidden)').first().getAttribute('data-slug');await page.click('#btn-theme-toggle');result.toggledTheme=await page.locator('html').getAttribute('class');
 await ready(page,origin+'/clinica/hems-una-heredia/');await page.click('#btn-open-report');await expect(page.locator('#report-modal')).toBeVisible();result.reportOpened=true;await page.click('#btn-close-report-modal');await expect(page.locator('#report-modal')).toBeHidden();result.reportClosed=true;result.errors=errors;return result;}finally{await ctx.close();}}
try{for(const width of [1280,390])for(const theme of ['light','dark']){const profile={width,theme};report.profiles.push(profile);for(const route of routes){const name=`${width}-${theme}-${route.replaceAll('/','_')}`;try{const a=await capture(profile,urls[0]+route,name+'-base');const control=await capture(profile,urls[0]+route,name+'-control');const controlDiff=await diff(a.png,control.png);if(controlDiff.different||a.errors.length||control.errors.length){report.visual.push({profile,route,control:controlDiff,errors:[...a.errors,...control.errors],conclusive:false});console.log('CONTROL FAILED',name);continue;}const b=await capture(profile,urls[1]+route,name+'-next');const actual=await diff(a.png,b.png);report.visual.push({profile,route,control:controlDiff,actual,errors:b.errors,conclusive:true});console.log(name,JSON.stringify(actual));}catch(e){report.visual.push({profile,route,error:String(e),conclusive:false});console.log('ERROR',name,String(e));}fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));}
 try{const a=await interaction(profile,urls[0]),b=await interaction(profile,urls[1]);report.interaction.push({profile,base:a,next:b,equal:JSON.stringify(a)===JSON.stringify(b)});}catch(e){report.interaction.push({profile,error:String(e)});}fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));}
 report.excludedExternal=[...excludedExternal];report.limitations.push('Ezoic/CMP external scripts suppressed; their availability and behavior are excluded from comparison.');report.remoteResources=[...remote.keys()];report.pass=remoteFailures.length===0&&report.visual.every(v=>v.conclusive&&!v.actual.different&&!v.errors.length)&&report.interaction.every(i=>i.equal&&!i.base.errors.length);fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));process.exitCode=report.pass?0:1;
}finally{await browser.close();for(const s of servers)s.close();}
